export const products = [
  {
    id: 1,
    name: 'Starter package',
    price: 185,
    imgSrc: '../../images/products/2.png',
    description: [
      '6x tomatoes',
      '1x lettuce',
      '1kg colored peppers',
      '1kg carrots',
      '1x butternut',
      '1x cabbage',
      '2x batches of spinach',
    ],
  },
  {
    id: 2,
    name: 'Standard package',
    price: 200,
    imgSrc: '../../images/products/1.png',
    description: [
      '12x tomatoes',
      '1kg green pepper',
      '1x lettuce',
      '2x butternut',
      '12x potatoes',
      '1x batch of spinach',
      '500g packet of chillies',
      '500g packet of green beans',
    ],
  },
  {
    id: 3,
    name: 'Gold package',
    price: 250,
    imgSrc: '../../images/products/3.jpg',
    description: [
      '12x tomatoes',
      '1kg green pepper',
      '1x lettuce',
      '2x butternut',
      '10kg potatoes',
      '1x batch of spinach',
      '500g packet of chillies',
      '500g packet of green beans',
    ],
  },
];

export const trendingProducts = [
  {
    id: 1,
    name: 'Starter package',
    price: 185,
    imgSrc: '../../images/products/1.png',
    description: [
      '6x tomatoes',
      '1x lettuce',
      '1kg colored peppers',
      '1kg carrots',
      '1x butternut',
      '1x cabbage',
      '2x batches of spinach',
    ],
  },
  {
    id: 4,
    name: 'Onions',
    price: 50,
    imgSrc: '../../images/products/onions.jpg',
    description: ['18 fresh onoins'],
  },
  {
    id: 5,
    name: 'Cucumber',
    price: 20,
    imgSrc: '../../images/products/cucumber.jpg',
    description: ['1 fresh cucumber'],
  },
  {
    id: 6,
    name: 'Broccoli',
    price: 25,
    imgSrc: '../../images/products/broccoli.jpg',
    description: ['1kg of fresh broccoli'],
  },
];
